apiVersion: monitoring.coreos.com/v1
kind: PodMonitor

metadata:
  name: api-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack

spec:
  namespaceSelector:
    matchNames:
      - rental

  selector:
    matchLabels:
      app: {{ .Values.rental.app}}
      component: server
      prometheus: "true"

  podMetricsEndpoints:
    - port: {{ .Values.rental.server.portName }}
      path: /metrics
      interval: 15s
