apiVersion: apps/v1
kind: Deployment

metadata:
  name: db
  namespace: rental

spec:
  replicas: 1

  selector:
    matchLabels:
      app: renter
      component: db

  template:
    metadata:
      labels:
        app: renter
        component: db
    
    spec:
      nodeSelector:
        role: database
      containers:
        - name: postgres
          image: postgres:18
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: renter-config
            - secretRef:
                name: renter-secret
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql

      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc


---
# service

apiVersion: v1
kind: Service

metadata:
  name: postgres
  namespace: rental

spec:
  selector:
    app: renter
    component: db

  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
