apiVersion: apps/v1
kind: Deployment

metadata:
  name: redis
  namespace: rental

spec:
  replicas: 1
  selector:
    matchLabels:
      app: renter
      component: redis

  template:
    metadata:
      labels:
        app: renter
        component: redis

    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379


