apiVersion: v1
kind: Service

metadata:
  name: server
  namespace: rental

spec:
  selector:
    app: renter
    component: server

  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP


