apiVersion: apps/v1
kind: Deployment

metadata:
  name: server
  namespace: rental

spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.maxSurge }}
      maxUnavailable: {{ .Values.maxUnavailable }}


  selector:
    matchLabels:
      app: renter
      component: server


  template:
    metadata:
      labels:
        app: renter
        component: server

    spec:
      topologySpreadConstraints:
        - maxSkew: {{ .Values.maxSkew }}
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: renter
              component: server
      serviceAccountName: api
      containers:
        - name: server
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          args:
            args:
            - gunicorn
            - config.wsgi:application
            - --bind
            - 0.0.0.0:8000
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          envFrom:
            - configMapRef:
                name: renter-config
            - secretRef:
                name: renter-secret
          startupProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 10
            failureThreshold: 20
          readinessProbe:
              httpGet:
                path: /ready
                port: 8000
              periodSeconds: 10
              timeoutSeconds: 2
              successThreshold: 1
              failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3


---
# service

apiVersion: v1
kind: Service

metadata:
  name: server
  namespace: rental

spec:
  selector:
    app: renter
    component: server

  ports:
    - port: 80
      targetPort: 8000
  type: ClusterIP

