apiVersion: apps/v1
kind: Deployment

metadata:
  name: beat
  namespace: rental

spec:
  replicas: 1

  selector:
    matchLabels:
      app: renter
      component: beat
    
  template:
    metadata:
      labels:
        app: renter
        component: beat

    spec:
      containers:
        - name: beat
          image: renter:latest
          imagePullPolicy: IfNotPresent
          args:
            - celery
            - -A
            - config.celery
            - beat
            - --loglevel=info
          
          envFrom:
            - configMapRef:
                name: renter-config
            
            - secretRef:
                name: renter-secret
