apiVersion: v1
kind: ConfigMap

metadata:
  name: renter-config
  namespace: rental

data:
  DEBUG: "True"
  DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1"

  POSTGRES_DB: renter
  POSTGRES_USER: postgres
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"

  REDIS_URL: "redis://redis:6379/0"
  CELERY_BROKER_URL: "redis://redis:6379/0"
