apiVersion: v1
kind: ConfigMap

metadata:
  name: renter-config
  namespace: rental

data:
  DJANGO_DEBUG: {{ .Values.config.djangoDebug | quote }}
  POSTGRES_USER: {{ .Values.config.postgresUser | quote }}
  DJANGO_ALLOWED_HOSTS: {{ .Values.config.djangoAllowedHosts | quote }}
  POSTGRES_DB: {{ .Values.config.postgresDb | quote }}
  POSTGRES_PORT: "5432"
  POSTGRES_HOST: "postgres"

  REDIS_URL: "redis://redis:6379/0"
  CELERY_BROKER_URL: "redis://redis:6379/0"
