apiVersion: batch/v1
kind: Job

metadata:
  name: server-job
  namespace: rental
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation

spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      labels:
        app: renter
        role: migration
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: IfNotPresent
          args:
            - python 
            - manage.py
            - migrate
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
            - secretRef:
                name: {{ .Release.Name}}-secret

