# kind-ingress-values.yaml
controller:
  hostPort:
    enabled: true
  service:
    type: NodePort
  publishService:
    enabled: false
  nodeSelector:
    ingress-ready: "true"
    kubernetes.io/os: linux
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
