namespace: renter
app: renter

replicas: 2

api:
  workers: 2

image:
  repositoryUrl: ""
  tag: ""
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "1"
    memory: "2Gi"

workerResources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "1"
    memory: "2Gi"

maxSurge: 2
maxUnavailable: 1

minReplicas: 2
maxReplicas: 5

maxSkew: 1

config:
  awsRegion: ap-south-1
  cidr_block: "10.20.0.0/16"