apiVersion: apps/v1
kind: Deployment

metadata:
  name: postgres
  namespace: rental

spec:
  replicas: 1

  selector:
    matchLabels:
      app: renter
      component: db
  
  template:
    metadata:
      labels:
        app: renter
        component: db
  

  containers:
    name: db
    image: postgres:16
    ports:
      - containerPort: 5432
    
    env:
      - name: POSTGRES_DB
        value: renter
      
      - name: POSTGRES_USER
        value: postgres
      
      - name: POSTGRES_PASSWORD
        value: helloworld

