apiVersion: apps/v1
kind: Deployment

metadata:
  name: worker
  namespace: rental

spec:
  replicas: 2

  selector:
    matchLabels:
      app: renter
      component: worker
    
  template:
    metadata:
      labels:
        app: renter
        component: worker

    spec:
      containers:
        - name: worker
          image: renter:latest
          imagePullPolicy: IfNotPresent
          args:
            - celery
            - -A
            - config.celery
            - worker
            - --loglevel=info
          
          envFrom:
            - configMapRef:
                name: renter-config
            
            - secretRef:
                name: renter-secret
