replicas: 2
api:
  workers: 2
image:
  repository: renter
  tag: latest
resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "1"
    memory: "2Gi"

config:
  djangoDebug: true
  djangoAllowedHosts: "localhost,127.0.0.1,renter.local,server.rental.svc.cluster.local"
  postgresUser: "postgres"
  postgresDb: "renter"

maxSurge: 2
maxUnavailable: 1
minReplicas: 2
maxReplicas: 10
maxSkew: 1

  

