apiVersion: apps/v1
kind: Deployment

metadata:
  name: api
  namespace: {{ .Values.namespace }}

spec:
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.maxSurge }}
      maxUnavailable: {{ .Values.maxUnavailable}}
  
  selector:
    matchLabels:
      app: {{ .Values.app }}
      component: api
    
  template:
    metadata:
      labels:
        app: {{ .Values.app}}
        component: api
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: {{ .Values.app }}
              component: api
      serviceAccountName: {{ .Values.app }}-api
      containers:
        - name: api
          image: "{{ .Values.image.repositoryUrl }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          args:
            - gunicorn
            - "config.wsgi:application"
            - --bind
            - "0.0.0.0:8000"
            - --workers
            - {{ .Values.api.workers | quote }}
            - --access-logfile
            - "-"
            - --error-logfile
            - "-"
          envFrom:
            - configMapRef:
                name: {{ .Values.app }}-config
            - secretRef:
                name: {{ .Values.app }}-secret
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          startupProbe:
            httpGet:
              path: /health/
              port: 8000
            periodSeconds: 10
            failureThreshold: 20
          readinessProbe:
              httpGet:
                path: /ready/
                port: 8000
              periodSeconds: 10
              timeoutSeconds: 2
              successThreshold: 1
              failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health/
              port: 8000
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

---
apiVersion: v1
kind: Service

metadata:
  name: api
  namespace: {{ .Values.namespace }}

spec:
  selector:
    app: {{ .Values.app }}
    component: api
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
