apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ .Values.app }}-config
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation

data:
  DJANGO_DEBUG: {{ .Values.config.djangoDebug | quote }}
  DJANGO_ALLOWED_HOSTS: {{ .Values.config.djangoAllowedHosts | quote }}
  POSTGRES_PORT: "5432"
