apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: {{.Values.app }}-ingress
  namespace: {{ .Values.namespace }}


spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: api
                port: 
                  number: 80
