apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
    name: {{ .Values.app }}-secret
    namespace: {{ .Values.namespace }}
    annotations:
      argocd.argoproj.io/sync-wave: "-1"
      argocd.argoproj.io/hook: PreSync
      argocd.argoproj.io/hook-delete-policy: BeforeHookCreation

spec:
    refreshInterval: 1h
    secretStoreRef:
        name: aws-secretsmanager
        kind: ClusterSecretStore
    target:
        name: {{ .Values.app }}-secret
        creationPolicy: Owner
    
    dataFrom:
        - extract:
            key: rental/prod
    data:
      - secretKey: POSTGRES_USER
        remoteRef:
          key: {{ .Values.config.rdsSecretName | quote }}
          property: username
      - secretKey: POSTGRES_PASSWORD
        remoteRef:
          key: {{ .Values.config.rdsSecretName | quote }}
          property: password
