name: Build and Deploy

on:
    pull_request:
        branches: [no-branch]
        types: [closed]
    push:
        branches: [no-branch]

permissions:
    contents: read
    packages: write

concurrency:
  group: production
  cancel-in-progress: true

jobs:
    build:
        if: >-
          github.event_name == 'push' ||
          (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v5
            
            - name: Setup docker
              uses: docker/setup-buildx-action@v4
            
            - name: Docker login
              uses: docker/login-action@v3
              with: 
                registry: ghcr.io
                username: ${{github.actor}}
                password: ${{secrets.GITHUB_TOKEN}}
            
            - name: Docker build and push
              uses: docker/build-push-action@v6
              with:
                context: .
                file: docker/Dockerfile.prod
                push: true
                tags: |
                    ghcr.io/${{github.repository}}:latest
                    ghcr.io/${{github.repository}}:${{github.sha}}
    
    deploy:
      needs: build
      runs-on: ubuntu-latest

      steps:
        - name: Setup Ssh
          run: |
            mkdir -p ~/.ssh
            echo "${{secrets.SSH_KEY_EC2}}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            echo "${{secrets.EC2_HOST_KEY}}" > ~/.ssh/known_hosts
        
        - name: Run Deploying Server
          run: |
            ssh ${{secrets.EC2_USER}}@${{secrets.EC2_HOST}} \
            "/home/${{secrets.EC2_USER}}/renter/deploy.sh ${{github.sha}}"
    
    verify:
      needs: deploy
      runs-on: ubuntu-latest

      steps:
        - name: Show deployed verison
          run: |
            echo "Version: ${{github.sha}}"
        
        - name: Health check
          run: |
            for i in {1..20}; do
              curl -f http://${{secrets.EC2_HOST}}/health/  && exit 0
              echo "waiting for application to restart"

              sleep 5

            done
            echo "Application startup failed"
            exit 1

