name: ECS Build and Deploy

# on:
#     pull_request:
#         branches: [main]
#         types: [closed]
#     push:
#         branches: [main]

on:
    workflow_dispatch:

permissions:
    id-token: write
    contents: read

concurrency:
    group: production
    cancel-in-progress: true

jobs:
    test_connection:
        runs-on: ubuntu-latest
        
        steps:
            - name: configure-aws
              uses: aws-actions/configure-aws-credentials@v5
              with:
                role-to-assume: ${{vars.AWS_DEPLOY_ROLE_ARN}}
                aws-region: ${{vars.AWS_REGION}}
            
            - name: Get aws sts identity
              run: aws sts get-caller-identity

